# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
- group: release-common
- name: path_in_configuration_repo
  value: 05/demoapp

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: templates
    type: github
    name: iremmats/azure-devops-templates
    ref: refs/heads/master
    endpoint: iremmats

stages:
- template: pipelines/pipeline-gitops.yaml@templates
  parameters:
    applicationName: demoapp
    repository: 'iremmats/hello-world'


